using System;
using System.Drawing;
using FocusShade;
class Tests {
    static int count;
    static void Check(bool value, string name) { if (!value) throw new Exception("FAIL: " + name); count++; Console.WriteLine("PASS: " + name); }
    static void Main() { try { Run(); } catch (Exception ex) { Console.WriteLine(ex.Message); Environment.Exit(1); } }
    static void Run() {
        var tray=typeof(SwitcherPolicy).GetMethod("IsTraySurface");
        Check(tray!=null && (bool)tray.Invoke(null,new object[] { "TopLevelWindowForOverflowXamlIsland","explorer" }),"tray overflow does not replace the real application target");
        Check(!(bool)tray.Invoke(null,new object[] { "TopLevelWindowForOverflowXamlIsland","ordinary-app" }),"ordinary app cannot impersonate the tray overflow");
        var popup=typeof(Geometry).GetMethod("Popup");
        Check(popup!=null,"popup placement supports a shared menu and settings anchor");
        Rectangle work=new Rectangle(-1920,-200,1920,1032); Point anchor=new Point(-15,800);
        Rectangle menu=(Rectangle)popup.Invoke(null,new object[] { anchor,new Size(180,120),work });
        Rectangle settings=(Rectangle)popup.Invoke(null,new object[] { anchor,new Size(340,330),work });
        Check(menu.Right==settings.Right && menu.Bottom==settings.Bottom && work.Contains(settings),"larger settings preserves bottom-right anchor on negative monitor");
        Check(work.Contains((Rectangle)popup.Invoke(null,new object[] { new Point(-1920,-200),new Size(340,330),work })),"top-left popup stays within working area");
        Rectangle area = new Rectangle(-1920, -200, 1920, 1080), full = new Rectangle(-1920, 200, 56, 56);
        Check(Geometry.Collapsed(full, area, DockEdge.Left, 6) == new Rectangle(-1920, 200, 6, 56), "negative monitor left strip");
        Check(Geometry.Collapsed(full, area, DockEdge.Right, 6).Right == area.Right, "right edge physical coordinates");
        Check(Geometry.Collapsed(full, area, DockEdge.Top, 6).Top == area.Top, "top edge");
        Check(Geometry.Collapsed(full, area, DockEdge.Bottom, 6).Bottom == area.Bottom, "bottom edge");
        Check(Geometry.Snap(full, area, 24) == DockEdge.Left, "snap negative coordinate");
        Check(Geometry.Snap(new Rectangle(-1000, 200, 56, 56), area, 24) == DockEdge.None, "interior stays expanded");
        Rectangle virtualArea = Rectangle.Union(area, new Rectangle(0, 0, 2560, 1440));
        Check(virtualArea.Left == -1920 && virtualArea.Width == 4480 && virtualArea.Top == -200, "virtual desktop union");
        ShadeState state = new ShadeState { Enabled = true, ShellView = true };
        Check(state.Suspended(DateTime.UtcNow), "task view remains after keys released");
        state.ShellView = false; state.PendingUntil = DateTime.UtcNow.AddSeconds(1);
        Check(state.Suspended(DateTime.UtcNow), "opening grace prevents early mask");
        state.PendingUntil = DateTime.MinValue; state.AltSwitch = true;
        Check(state.Suspended(DateTime.UtcNow), "alt tab suspension");
        state.Emergency();
        Check(!state.Enabled && !state.AltSwitch && !state.ShellView && !state.Suspended(DateTime.UtcNow), "emergency clears mask and suspension");
        Check(SwitcherPolicy.ForegroundShellView("XamlExplorerHostIslandWindow",true), "Windows 11 unnamed foreground task view host");
        Check(!SwitcherPolicy.ForegroundShellView("XamlExplorerHostIslandWindow",false), "non shell app is not task view");
        Check(!SwitcherPolicy.ForegroundShellView("CabinetWClass",true), "ordinary Explorer remains masked");
        var drag=new DragSession(); drag.Start(); drag.Moved=true; drag.Cancel();
        Check(!drag.Active && !drag.Moved, "hidden or capture lost button cancels drag");
        bool visible=true; state.Enabled=true;
        Safety.FailOpen(delegate { throw new UnauthorizedAccessException("diagnostic write failure"); },delegate(Exception ex) { state.Emergency(); visible=false; });
        Check(!visible && !state.Enabled, "update failure restores desktop before diagnostic logging");
        state.Enabled=true; state.PendingUntil=DateTime.MinValue; state.EndAltSwitch(DateTime.UtcNow);
        Check(!state.Suspended(DateTime.UtcNow), "ordinary Alt release does not expose desktop");
        state.AltSwitch=true; state.EndAltSwitch(DateTime.UtcNow);
        Check(!state.AltSwitch && state.Suspended(DateTime.UtcNow), "AltTab release retains only switch ending grace");
        Check(SwitcherPolicy.MaskDuringAltTab(true), "AltTab keeps black mask outside selector");
        Check(!SwitcherPolicy.MaskDuringAltTab(false), "disabled mask stays disabled during AltTab");
        Check(!ButtonVisuals.CreateRegion(new Size(56,56)).IsVisible(0,0), "round button excludes rectangular corners");
        Check(ButtonVisuals.CreateRegion(new Size(56,56)).IsVisible(28,28), "round button center hit target");
        Check(!ButtonVisuals.CreateRegion(new Size(6,56)).IsVisible(0,0), "docked strip has rounded end");
        Check(ButtonVisuals.CreateRegion(new Size(6,56)).IsVisible(3,28), "docked strip center hit target");
        Check(ButtonVisuals.Alpha(false)==230 && ButtonVisuals.Alpha(true)==153, "90 and 60 percent opacity");
        var dragMethod=typeof(SwitcherPolicy).GetMethod("DragActive");
        Check(dragMethod!=null && (bool)dragMethod.Invoke(null,new object[]{false,true,false,false}),"native move loop identifies a drag before the start event arrives");
        Check((bool)dragMethod.Invoke(null,new object[]{false,false,true,true}),"application mouse capture and held left button identify custom dragging");
        Check(!(bool)dragMethod.Invoke(null,new object[]{false,false,false,true}),"a held mouse button alone cannot exempt a shell host");
        Check(!(bool)dragMethod.Invoke(null,new object[]{false,false,true,false}),"released mouse capture alone cannot keep a drag active");
        Rectangle monitor=new Rectangle(-1920,-200,1920,1080),bar=new Rectangle(-1920,-200,1920,360);
        Check(SwitcherPolicy.IsSnapBar("XamlExplorerHostIslandWindow","",true,true,bar,monitor),"top snap bar is allowed during app drag");
        Check(!SwitcherPolicy.IsSnapBar("XamlExplorerHostIslandWindow","",false,true,bar,monitor),"ordinary app cannot impersonate snap bar");
        Check(!SwitcherPolicy.IsSnapBar("XamlExplorerHostIslandWindow","",true,false,bar,monitor),"unrelated shell host outside drag is not snap bar");
        Check(!SwitcherPolicy.IsSnapBar("XamlExplorerHostIslandWindow","",true,true,monitor,monitor),"full screen shell host is not top snap bar");
        Check(!SwitcherPolicy.IsSnapBar("XamlExplorerHostIslandWindow","Task View",true,true,bar,monitor),"task view is not snap bar");
        Check(WindowEvents.IsWindowObject(0,0),"top level window destruction may clear layer baseline");
        Check(!WindowEvents.IsWindowObject(-4,1),"client object destruction does not clear window baseline");
        Check(!WindowEvents.IsWindowObject(0,1),"child object destruction does not clear window baseline");
        Check(SwitcherPolicy.IsSystemPanel("Windows.UI.Core.CoreWindow","SearchHost"),"Windows Search is a system panel rather than a promoted app");
        Check(SwitcherPolicy.IsSystemPanel("Windows.UI.Core.CoreWindow","StartMenuExperienceHost"),"Start menu is a system panel rather than a promoted app");
        Check(!SwitcherPolicy.IsSystemPanel("Windows.UI.Core.CoreWindow","ordinary-app"),"ordinary CoreWindow is not exempted from application layers");
        Check(!SwitcherPolicy.IsSystemPanel("XamlExplorerHostIslandWindow_WASDK","explorer"),"empty taskbar proxy is not a Start or Search panel");
        Console.WriteLine("TOTAL " + count + " passed");
    }
}
